### ISSUE TITLE
Multiple errors due to incorrect $PATH

### ISSUE THREAD

**Issue by covntestark** [Knightfall01/Dotfiles-for-i3-Hyprland#3]
Hello, first of, thank you for your configuration and contribution. However there are config issues arising due to most of these files having been saved with your default path naming in  "~/*".

Normally it would be simple, but due to multiple errors and recursions, it becomes difficult and makes one unwilling to incorporate it due to possible future errors that may go missed.

**Comment by knightfallxz** [comment]
Thank you for bringing up this issue, and I appreciate your feedback. I understand your concerns regarding the default path naming "~/*" causing problems . Can you say exactly where you have encountered this issue ? . Thanks again , thank you for using my config

**Comment by covntestark** [comment]
Well for started your username is now causing alot of duplicate entries in alot of my environment variables..... I mean its my fault for so casually using your config, but it is ridiculous.... I am pretty much going  to have to reinstall the system just to avoid any security risks... 

[ knightfall home/USERNAME/ config/ emacs/bin knightfal echo $fish_user_paths freetype2.sh debuginfod.sh perlbin.sh locale.sh jre.sh sudo sh /etc/profile.d/jre.sh cat  /etc/profile.d/jre.sh perlbin.csh d/PackageKit.sh gpm.sh gpm.sh /home/USERNAME/.config/emacs/bin home/USERNAME/.bin /home/USERNAME/.local/bin /home/knightfall/.local/bin /home/knightfall/.config/emacs/bin /home/knightfall/.bin /usr/local/sbin /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl/corelist  PATH= usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl/ knightfall knightfall home/knightfall/.local/bin XDG_RUNTIME_DIR XDG_RUNTIME_DIR ]

**Comment by knightfallxz** [comment]
I will work in it on the next commit . Thank you , ig I have to change couple of things , I will .

**Comment by knightfallxz** [comment]
I have corrected it in the latest commit , sorry for your troubles.
