### ISSUE TITLE
Add auto install script 

### ISSUE THREAD

**Issue by tahadostifam** [Knightfall01/Dotfiles-for-i3-Hyprland#5]
This is one the most awesome Hyprland configs i have been ever seen!
If you add a script to be installed easily it would be better =)

**Comment by knightfallxz** [comment]
Thanks , I know its been a while since i updated it share yours i would be glad to see it and That's the hard part with the hyprland configs it sometimes has installation errors . And there are some lines that have to be commented out for the config to work on the latest version of hyprland

**Comment by tahadostifam** [comment]
> Thanks , I know its been a while since i updated it share yours i would be glad to see it and That's the hard part with the hyprland configs it sometimes has installation errors . And there are some lines that have to be commented out for the config to work on the latest version of hyprland

Yes unfortunately😅
Recently i made my own HyprLand config and the installation commands are inconsistent and inappropriate. The same problem is up in my config too.

We need to find out a unraveling method. For example we can list the packages we used and fetch them of the repositories of different linux distros like AUR or OpenSUSE.

Any better idea?
